config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'entries#index'

  resources :entries, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  
  validates :title, presence: true
  validates :text, presence: true

  has_one_attached :photo
  validates :photo, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end


  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
    end
  end
  
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

    def index
      @entries = Entry.all
    end

    def new
      @entry = Entry.new
    end

    def create
      @entry = Entry.new(entry_params)
      if @entry.save
        redirect_to root_path, notice: '記録が正常に保存されました。'
      else
        render :new
      end
    end
  
    private
    def entry_params
      params.require(:entry).permit(:title, :photo, :text)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/index.html.erb
<div class="contents row">
  <% @entries.each do |entry| %>
    <div class="content_post">
      <% if entry.photo.attached? %>
        <%= image_tag entry.photo, class: 'message-image' %>
      <% end %>
      <p><%= entry.text %></p>
      <span class="name">
        <%= entry.title %>
      </span>
    </div>
  <% end %>
</div>

app/views/entries/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>記録の情報を入力</h3>
    <%= form_with model: @entry, url: entries_path, local: true do |form| %>
      <div class="img-upload">
        <div class="weight-bold-text">
          記録画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= form.file_field :photo %>
        </div>
      </div>

      <div class="new-items">
        <div class="weight-bold-text">
          タイトル
          <span class="indispensable">必須</span>
        </div>
        <%= form.text_area :title, placeholder: "title" %>
      </div>
     
      <div class="new-items">
        <div class="weight-bold-text">
          テキスト
           <span class="indispensable">必須</span>
        </div>
        <%= form.text_area :text, placeholder: "text", rows: "10" %>
      </div>

      <%= form.submit "記録する" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KIROKU</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">KIROKU</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            <%= link_to "記録する", new_entry_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright KIROKU 2023.
      </p>
    </footer>
  </body>
</html>